server:
 port: 8082
spring:
 application:
  name: service-store-productos
eureka:
 client:
  fetch-registry: true
  service-url:
   defaultZone: http://localhost:8761/eureka
ribbon:
 ConnectTimeout: 3000
 ReadTimeout: 10000
hystrix:
 command:
  default:
   execution:
    isolation:
     thread:
      timeoutInMilliseconds: 40000

